config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only:[:index, :show, :edit, :update, :destroy]
  resources :books, only:[:index, :show, :create, :edit, :update, :destroy]
  root 'homes#top'
  get 'home/about' => "homes#about", as: "homes_about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image

  has_many :books
  validates :name, uniqueness: true, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except:[:top, :about]
  before_action :config_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

  def config_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.new
    @detail = Book.find(params[:id])
  end

  def create
    @book = current_user.books.new(book_params)
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      @user = current_user
      render "books/index"
    end
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @book = Book.new
    @user = current_user
    @users = User.all
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_index.html.erb
<h2>Books</h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user, :profile_image, size: "40x40", fallback: "no-image.jpg" %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_new.erb
<h2>New book</h2>
<div class="form-group">
  <%= form_with model: book, local: true do |f| %>
    <div class="field">
      <%= f.label :title, "Title" %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :body, "Opinion" %>
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <%= f.submit class: "btn btn btn-success" %>
  <% end %>
</div>

app/views/books/_new.html.erb
<h2>New book</h2>
<div class="form-group">
  <%= form_with model: book, local: true do |f| %>
    <div class="field">
      <%= f.label :title, "Title" %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :body, "Opinion" %>
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <%= f.submit class: "btn btn btn-success" %>
  <% end %>
</div>

app/views/books/_show.html.erb
<h2>Book detail</h2>
<table class="table">
  <tbody>
    <tr>
      <td>
        <%= link_to user_path(book.user) do %>
          <%= attachment_image_tag book.user, :profile_image, size: "40x40", fallback: "no-image.jpg" %>
          <p><%= book.user.name %></p>
        <% end %>
      </td>
      <td><%= link_to book.title, book_path(book) %></td>
      <td><%= book.body %></td>
      <% if book.user == current_user %>
        <td><%= link_to "Edit", edit_book_path(book), class: "btn btn-sm btn-success" %></td>
        <td><%= link_to "Destroy", book_path(book), class: "btn btn-sm btn-danger", method: :delete, "data-confirm" =>"本当に削除しますか？" %></td>
      <% end %>
    </tr>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="container">
  <div class="col-md-6 mx-auto">
    <h2>Editing Book</h2>
    <%= render "layouts/errors", model: @book %>
    <div class="form-group">
      <%= form_with model: @book, local: true do |f| %>
        <div class="field">
          <%= f.label :title, "Title" %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="field">
          <%= f.label :body, "Opinion" %>
          <%= f.text_area :body, class: "form-control" %>
        </div>
        <%= f.submit class: "btn btn btn-success" %>
      <% end %>
    </div>
    <div class="link">
      <p><%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path %></p>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <%= render "layouts/errors", model: @book %>
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: @user %>
      <%= render "books/new", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <%= render "books/index", books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: @detail.user %>
      <%= render "books/new", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <%= render "books/show", book: @detail %>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class= "container text-center">
  <h1>Welcome to <strong><i class="fas fa-book"></i>Bookers</strong>!</h1>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="col-md-6 mx-auto">
    <h1>welcome to <strong><i class="fas fa-book"></i>Bookers</strong> !!</h1>
    <p>In <strong><i class="fas fa-book"></i>Bookers</strong>,</p>
    <p>you can share and exchange your opinions , inpressions , and emotions</p>
    <p>about various books!</p>

    <%= link_to "Log in", new_user_session_path, class: "d-block btn btn-sm btn-info mx-5" %>
    <%= link_to "Sign up", new_user_registration_path, class: "d-block btn btn-sm btn-success mx-5" %>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if model.errors.any? %>
  <div style="color: red;">
    <h2><%= pluralize(model.errors.count, "error") %> prohibited this obj from being saved:</h2>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="mt-5">
  <p class="text-center">CopyRight Infratop.inc</p>
</footer>

app/views/layouts/_header.html.erb
<header class="mb-3">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <%= link_to "Bookers", root_path, class: "navbar-brand" %>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user), class: "nav-link text-light" do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%= link_to users_path, class: "nav-link text-light" do %>
              <i class="fas fa-users"></i> Users
            <% end %>
          </li>
          <li>
            <%= link_to books_path, class: "nav-link text-light" do %>
              <i class="fas fa-book-open"></i> Books
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, class: "nav-link text-light", method: :delete do %>
              <i class="fas fa-sign-out-alt"></i> logout
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path, class: "nav-link text-light" do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%= link_to homes_about_path, class: "nav-link text-light" do %>
              <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
              <i class="fas fa-user-plus"></i> sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path, class: "nav-link text-light" do %>
              <i class="fas fa-sign-in-alt"></i> login
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
  <p class="text-success"><%= notice %></p>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/users/_index.html.erb
<h2>Users</h2>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td>
          <%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no-image.jpg" %>
        </td>
        <td><%= user.name %></td>
        <td><%= link_to "Show", user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<h2>User info</h2>

<%= attachment_image_tag user, :profile_image, size: "100x100", fallback: "no-image.jpg" %>
<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>

<%= link_to edit_user_path(user), class: "btn btn-sm btn-outline-secondary d-block" do %>
  <i class="fas fa-user-cog"></i>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="col-md-6 mx-auto">
    <h2>User info</h2>
    <%= render "layouts/errors", model: @user %>
    <div class="form-group">
      <%= form_with model: @user, local: true do |f| %>
        <div class="field">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="field">
          <%= f.label :profile_image, "Image", class: "d-block" %>
          <%= f.attachment_field :profile_image %>
        </div>
        <div class="field">
          <%= f.label :introduction, "Introduction" %>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <%= f.submit class: "btn btn btn-secondary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: @user %>
      <%= render "books/new", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <%= render "users/index", users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: @user %>
      <%= render "books/new", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <%= render "books/index", books: @books %>
    </div>
  </div>
</div>